### PR TITLE
add link to privacy policy

### PR DESCRIPTION
**Pull request by rupeshparab**
Ref - https://github.com/benetech/MathShare/issues/1075

### CODE REVIEW

**Comment by johnhbenetech** [comment]
@alexrcabral can we get input on this?

**Comment by alexrcabral** [comment]
@jscholes I'm unclear on where you're encountering the duplication. Currently the universal footer only includes the Twitter link, Youtube link, the proposed Privacy Policy link, and the Copyright text. There is a "footer" exclusively on the initial informational landing page, but which isn't part of the footer repeated on the rest of the site. 

For markup, what would you suggest as best practice for a universal footer?

**Comment by jscholes** [comment]
@alexrcabral Sorry, I was confusing the two footer components.  I think a universal footer is potentially a good idea, to avoid this exact situation.  If you're starting to copy links over from one footer to another, maybe just pick one design and use it everywhere?  Helps with consistency.

**Comment by alexrcabral** [comment]
@jscholes Thanks James, & noted. I've opened issue #1150 to address this

@rupeshparab Good to proceed with this pull

**Pull request merged**
