### PR TITLE
#1059 - add headings to dashboard page

### PR DESCRIPTION
**Pull request by rupeshparab**
Added headings to the dashboard page
Ref - https://github.com/benetech/MathShare/issues/1059

### CODE REVIEW

**Comment by rupeshparab** [comment]
@jscholes 
Sorry, I missed adding the empty alt to make the image decorative.
Have added it now

**Comment by jscholes** [comment]
@rupeshparab It still makes no sense.  There is no ``, so nothing to add empty alt text to.  The `alt` attribute cannot be added to a `<span>`.  How is the image being rendered?

**Comment by rupeshparab** [comment]
@jscholes 
The content of the span tag is a textbook emoji
I had got this error from the jsx-a11y linter:
> Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby.eslint(jsx-a11y/accessible-emoji)

So I added the image role to it

**Comment by jscholes** [comment]
@rupeshparab Oh I see.  In this case, it doesn't add anything to the page.  So just put `aria-hidden="true"` on the `<span>` instead.

**Comment by rupeshparab** [comment]
@jscholes 
thanks, have added aria-hidden="true" to the span

**Pull request merged**
