### PR TITLE
TTS Personalisation

### PR DESCRIPTION
**Pull request by rupeshparab**
Ref - https://github.com/benetech/MathShare/issues/1006

### CODE REVIEW

**Comment by johnhbenetech** [comment]
copying over james's feedback from previous PR:

Re: personalisation, the TTS speed slider doesn't make any sense to a screen reader user:

1. It has the word "Slower" before it, and "Faster" after it.  I'm not sure what these represent.
2. For a screen reader user, the values go from 0.5 to 1.5.  What significance do those numbers have?  Why not 0 to 1, or the more standard 0 to 100?
3. When I change the slider's value, the `aria-valuenow` property contains up to 16 decimal places.  I have no idea what the number 0.8500000238418579 represents in terms of TTS speed.

If the aim here is to have specific speed presets, `aria-valuetext` can be used to apply those to the slider based on a specific value.  But there are 21 possible positions for this slider to be in, so I don't think that is currently the case.  Indeed, the fact that there are 21 positions is in itself confusing, because it implies a non-standard step value.

@alexrcabral can you provide guidance on points 1 and 2 from james? I think the original discussion was since there is some understood 'normal' speed, there should be consideration as deviation from normal (i.e. half the speed, twice the speed), but I can also see using 0-100 where 50 is the default value. Let us know the final decision for:
* the copy for the endpoints
* the range of the numbers
* how many steps should be present

@rupeshparab can you look into checking how you established step size to ensure it's standard, and then also (Assuming alex wants standard steps) use aria-valuetext to label steps appropriately

**Comment by rupeshparab** [comment]
@johnhbenetech 
I have changed the values on frontend, now the range of values will be 0 - 100 and step size is 5, so the values can be 0, 5, 10, ..., 95, 100

I can define label for steps once Alex shares the text he wants for it

**Comment by alexrcabral** [comment]
Thanks @rupeshparab 

From my understanding, the Slower / Faster question is around how it's labelled more-so than the copy of the labels. 

@jscholes “Slower” and “Faster” represent the directionality of the slider. Labels on either end are generally best practice for cognitive ease visually, e.g. with semantic differentials scales. Is there a way to label it differently, or more effective copy to use, so it is less confusing for a screen reader user?

**Comment by alexrcabral** [comment]
@rupeshparab Labels of individual steps should be spoken out as percentages, e.g. "0%, 5%, 10%"

**Comment by johnhbenetech** [comment]
Also @rupeshparab since the AWS speed range goes from 20-200 we will have to come up with a mapping between our Mabel's and their speeds.

So on the mathshare side, the user will only be presented with 0-100 by increments of 5.

It maps to AWS as follows.
Our 0 = AWS 20
Our 50 = AWS 100
Our 100 = AWS 180

Where our 5 increments are increments of 8 in AWS

**Comment by jscholes** [comment]
> Labels of individual steps should be spoken out as percentages, e.g. "0%, 5%, 10%"

In that case @rupeshparab, you won't need any aria-valuetext attribute at all, only aria-valuenow set to a whole number representing the current step.  But that's if you're using an ARIA-based slider, which will not work on a touch screen for screen reader users, may not work that well for speech recognition users, etc.  Is there a reason we're not just using an `<input>` with `type="range"` here?

> “Slower” and “Faster” represent the directionality of the slider. Labels on either end are generally best practice for cognitive ease visually, e.g. with semantic differentials scales. Is there a way to label it differently, or more effective copy to use, so it is less confusing for a screen reader user?

I'm not sure.  Let's discuss on a call.

**Comment by rupeshparab** [comment]
@johnhbenetech 
I have updated the value calculation so that the value stored in backend is in the range of 0.2 to 1.8, if you had previously saved a speed, it would show a different value on the slider now.

@jscholes 
I have used rc-slider for TTS speed
It has inbuilt accessibility support, it is showing the current value using aria-valuenow

you can checkout the demo of rc-slider here: http://react-component.github.io/slider/?path=/story/rc-slider--slider

**Comment by alexrcabral** [comment]
@rupeshparab Since there's currently not a better way to handle the slider axis labels, continue as-is with the Slower/Faster.

@jscholes I have time set aside at the beginning of the meeting tomorrow to discuss TTS Personalization, so we can touch base on this then to determine if there's a better alternative.

**Comment by jscholes** [comment]
@rupeshparab I understand, but I'm saying that it is technically impossible to make an ARIA-based slider accessible for screen reader users on a touch screen.  It's not a limitation of React or any of its libraries, it's a hard technical blocker because the keyboard events required to move the slider are not fired by touch-based interactions.  So my question still stands -- could we use an `<input>` with `type="range"`?  It can be styled however it needs to be.

**Comment by rupeshparab** [comment]
@jscholes 
got it, I think we can switch to the input range slider

**Comment by rupeshparab** [comment]
@jscholes 
I have changed the slider to an input range based slider

**Comment by jscholes** [comment]
@rupeshparab Great.  We're waiting on @alexrcabral to provide some updated mock-ups for this modal following an on-call discussion yesterday, so I will test once those have been implemented.

**Comment by alexrcabral** [comment]
Mockups and updated scoping in the works, and should be out later today.

**Comment by alexrcabral** [comment]
@rupeshparab Updated mockups and scoping of slider: 

Mockup showing a slider with five tick marks. The first labelled Slowest, the middle labelled Medium, the last labelled Fastest. On the right of the slider is a text box with 50% currently inside it. The marker is currently set in the middle of the bar at the Medium tick mark.

The biggest change is the labels now appear below the slider, along with 5 tick marks to help with visual estimation. The first tick mark should be labelled “Slowest”, the middle tick mark should be labelled “Medium”, and the final tick mark should be labelled “Fastest.” 

The slider should step from 0%-100% on our scale by 5% increments, which are spoken out by the screen reader. The first (0%), middle (50%), and final (100%) increments should also speak out the corresponding labels, e.g. when stepping through, it should read out “45%, 50% - Medium, 55%…” 

The box to the right should be an interactible text box, both as a readout of the existing slider placement, as well as a way to enter a desired number to move the marker to a specific percentage. The percentage symbol in the text box should be static. Only numbers (one to two digit integers) can be entered, and if someone enters a number that is between steps, it should round to the nearest step (e.g. if someone types “53” and submits it (e.g. presses enter), it should round to 55%. 

Appearance: 

Mockup of Text to Speech speed setting in context, listed under the Text to Speech heading below General personalization settings.

The slider itself should be centered vertically with the “Speed” label and horizontally with the dropdown bars from the other personalization settings. The slider is medium grey (#D8D8D8) with darker border (#979797), and the tick marks below are short lines the same color as the slider border (#979797). 

The marker on the slider should look exactly like the marker in the mockup, and should change to blue when in an active state, e.g. when clicked and held.

Same marker with center in lighter blue tint with the outline of the shape in a darker blue.

@jscholes Let me know if any of this is different than what you were expecting and needs to be changed.

**Comment by rupeshparab** [comment]
I have updated the Slider according to the mockup: 
image

**Comment by alexrcabral** [comment]
It's looking good, one thing: 

> The slider itself should be centered vertically with the “Speed” label and horizontally with the dropdown bars from the other personalization settings. 

Could you please fix it so the slider matches horizontally with the dropdown bars from the other personalization settings for consistency? As in the bar itself the same width as the dropdown.

Mockup of Text to Speech speed setting in context, listed under the Text to Speech heading below General personalization settings. The slider bar is the same width as the dropdowns.

**Comment by rupeshparab** [comment]
@alexrcabral 
I have pushed a CSS fix

image

**Comment by alexrcabral** [comment]
Great, thanks @rupeshparab!

**Comment by johnhbenetech** [comment]
deploying to QA for testing. Any technical/a11y remediation will be broken out into separate issues/PRs

**Comment by johnhbenetech** [comment]
Hi @Sanjog1605 , can you recheck this. We made a recent update to modals which hopefully should fix this

**Pull request merged**
