### PR TITLE
#113: Made math field shrink back

### PR DESCRIPTION
**Pull request by afijal**

### CODE REVIEW

**Comment by pawelcieszko** [comment]
it seems there is a problem with annotation section just after loading the page (it is hidden but it becomes visible after typing in math editor.

**Comment by dserkowski** [comment]
image

**Comment by dserkowski** [comment]
I have found another issue. After removing high expression and then clicking "Clear all" button I have got the following view:
screenshot from 2018-06-26 14-48-29

**Comment by oskarhinc** [comment]
@afijal I think this PR is outdated. Can I close it?

**Comment by afijal** [comment]
@oskarhinc  sure go ahead

**Comment by oskarhinc** [comment]
I'm closing because it's outdated.

**Pull request closed without merging**
