### PR TITLE
#844 - add archived sets page

### PR DESCRIPTION
**Pull request by rupeshparab**
A new page for Archived Sets has been added, most of the HTML structure from Dashboard has been reused here.

Description of problem statement can be found here: https://github.com/benetech/MathShare/issues/844

### CODE REVIEW

**Comment by rupeshparab** [comment]
I have resolved the conflicts with development branch

**Comment by jscholes** [comment]
@rupeshparab Sorry, I didn't spot the review request on 7 Jan.  Looking at this now!

**Comment by rupeshparab** [comment]
I have added the aria-labelledby attribute, will wait for @benetechMatt to give the correct text to undo archive

**Comment by benetechMatt** [comment]
“Restore” for moving sets from the archive to active

**Comment by rupeshparab** [comment]
I have fixed the Restore text and also added few more changes of another task which was related to this change
https://github.com/benetech/MathShare/issues/1065

**Comment by jscholes** [comment]
@rupeshparab I don't think moving the example set is related to set archival at all.  For ease in reviewing, can we keep PRs as specific as possible?

**Comment by rupeshparab** [comment]
@jscholes 
Sure, will keep the PRs separate from now on
Thought of using one PR as the same view was being updated

**Pull request merged**
