### PR TITLE
Problem Set Actions

### PR DESCRIPTION
**Pull request by rupeshparab**
Ref:
https://github.com/benetech/MathShare/issues/1129
https://github.com/benetech/MathShare/issues/1094
https://github.com/benetech/MathShare/issues/1131
https://github.com/benetech/MathShare/issues/1086

This has a corresponding backend change, once this PR is approved, I will deploy both at the same time

### CODE REVIEW

**Comment by jscholes** [comment]
@rupeshparab Which PR on the backend side is required to run this locally?

**Comment by johnhbenetech** [comment]
@jscholes should be https://github.com/benetech/MathShareBackend/pull/82

**Comment by alexrcabral** [comment]
@jscholes to two of your points: 

3. This is more scoping than dev. There are different ways we could split these controls with different benefits and drawbacks (e.g. splitting between share settings and personal settings, at the cost of unauthenticated users), but that’s more of a larger scoping issue and a future discussion rather than an immediate change for this PR.

4. What is the item currently contained within the “Actions for this Problem Set” list? That was the old label for the list of possible share options (e.g. permalink, Google Classroom, Teams). The “More Options” dropdown should contain one item in the /solve view, two items in the /edit view, including the Share My Answers (see #1086). @rupeshparab I also want to make sure you're referencing the correct scoping, which should be my last comment on that issue with the four mockups (#1086).

**Comment by rupeshparab** [comment]
@jscholes 

> The "Problems in this Set" heading is still positioned before "Problem set controls:"

I have moved the heading after the controls

> The problem set controls are not in a list.

There are 3 controls, 2 toggles need to be shown in a column and the palette chooser button in another column, I have created 2 lists and have added common aria-label to both lists, let me know if I need to change it.

> The "More Options" dropdown can't be collapsed once expanded.

I have fixed this, previously if the toggle was being clicked it wasn't closing the dropdown

> It has no programmatically applied label.

I am not sure how this label is to be added, could you point me to any similar example of applying label to the modal?

> The first heading is at level 3 instead of level 1.

All of our existing modals have an h3 heading, but I have changed this to h1

> The URL field receives focus automatically

I have fixed the focus issue, now the focus will go to heading when the modal opens

> The control to display the URL for sharing and allow it to be copied doesn't reuse

I have changed the component just to a button without any input box on basis of the updated mockup, I think no changes will be required for this

> The "Close" button is unnecessarily wrapped inside a

removed footer from this modal





@alexrcabral 

> What is the item currently contained within the “Actions for this Problem Set” list?

 “Actions for this Problem Set” is the screen reader only heading for the problem set action section shown to problem set creators, attaching a screenshot of the items currently present in this container (2 Toggles and Palette chooser button)

image

Also, I went through https://github.com/benetech/MathShare/issues/1086 and made the recent updates on basis of the mockup in the share options

image

**Comment by alexrcabral** [comment]
@rupeshparab Thanks for the clarification! The two toggles and palette chooser button are presented correctly from a visual standpoint.

**Comment by jscholes** [comment]
> I have created 2 lists and have added common aria-label to both lists, let me know if I need to change it.

There's no need for semantic structure to mirror the two-column layout here, and having two lists will just increase screen reader verbosity.  Let me know if you can't fix this with CSS and I can give you an ARIA pattern, but I'd prefer that there be one list if at all possible.

> I have fixed this, previously if the toggle was being clicked it wasn't closing the dropdown

Still doesn't work for me.

> I am not sure how this label is to be added, could you point me to any similar example of applying label to the modal?

Just use either `aria-label` on the modal container, or `aria-labelledby` on the container referencing the ID of the modal's title heading.  The second one is prefered.

> All of our existing modals have an h3 heading, but I have changed this to h1

Do you mean that you've changed all modals to use an h1?  Because no modal should begin with an h3.

> I have changed the component just to a button without any input box on basis of the updated mockup, I think no changes will be required for this

This triggers a really confusing alert pattern when activated.  The page tries to focus the alert's heading, but it can't because the button is inside a modal.  Again, there should be a single component for share-link-related functionality, e.g. with properties to show the input or just a button, which uses an ARIA live announcement.

In addition, when not logged in, the live region announcement after pressing the copy button doesn't work, because for some reason pressing the button moves focus to the link input which interrupts the feedback.

**Comment by rupeshparab** [comment]
@jscholes 
I have fixed most of the issues. I have created a separate task for fixing modals which are not part of this PR: https://github.com/benetech/MathShare/issues/1224

**Comment by rupeshparab** [comment]
@jscholes 
I have fixed the issue of focus moving out of the modal, now the focus should stay on the button clicked to copy the link
Also, I have removed rendering of empty list and changed the h2 header to the text suggested.

Will wait for suggestion on the text for modal

**Comment by johnhbenetech** [comment]
@alexrcabral please supply copy for 2

**Comment by jscholes** [comment]
@rupeshparab The heading text shouldn't change.  It should always read "Problems in this Set", with "No problems added yet." and the add problem button underneath.

A couple of other things:

1. The " Share My Answers" action button doesn't seem to do anything.
2. When I've copied the URL to the clipboard using the button in the modal, subsequent button presses don't cause screen reader speech feedback to be spoken.  This is because the live region text isn't updated, so a screen reader doesn't recognise any change.  We should try clearing the text of the region first, before setting the message content.

**Comment by rupeshparab** [comment]
@jscholes 
I have moved the 'No problems added yet.' text to a h3 heading below 'Problems in this Set'

'Share My Answers' button opens up a modal similar to 'Share Problem Set'. It is used to generate a solution link to the problem set (link used by the students to share edit version of their solution).

I have added cleanup of aria-live text before setting text

**Comment by alexrcabral** [comment]
@jscholes I think that copy is accurate for what it's requesting. "share your finished work with the link below" followed by a button clearly labelled "Copy Link URL". It calls out all three options which correspond to their buttons (Google Classroom, Microsoft Teams, Link). The fact that the link is contained within the button I would expect to be intuitive, given the button label. 

The call to action being "press the button to share" or "copy the link using the button below to share" could lead people to believe they only have to press the button rather than share it, and since there are multiple ways of sharing a link (or saving it to share later), it might be best to refer to it more generally.

**Comment by jscholes** [comment]
@alexrcabral At the most basic level, the copy text is not accurate if it tells a user that there is a link below when there isn't one.  There's a button to copy a link, but no link.  There was a link, and I didn't think it was a bad idea to have both the link and the button, but @rupeshparab removed the link in favour of a single button.

@rupeshparab:

> I have moved the 'No problems added yet.' text to a h3 heading below 'Problems in this Set'

There should be no h3, it should just be plain text in a `<div>` or whatever.  Heading mark-up is inappropriate because there are no logical children of that heading.  Once that's fixed, I'll test the ARIA live changes, unless @alexrcabral decides that the link should be brought back.  In which case, to echo what I've already said, there should be one single component to present a share link and copy button that works the same wherever it is used.

**Comment by jscholes** [comment]
Also, @rupeshparab:

> 'Share My Answers' button opens up a modal similar to 'Share Problem Set'.

I get that, and that's what I expect.  I'm just saying that when I press it, nothing happens.  If a dialog does open, my focus isn't moved into it.

**Comment by rupeshparab** [comment]
@jscholes 
I have changed h3 to div

Regarding the 'Share My Answers' modal, I think it is not working for you because your backend might not be updated. I had pushed few changes to the backend PR: https://github.com/benetech/MathShareBackend/pull/82

**Comment by johnhbenetech** [comment]
@jscholes I know you are using the docker registry approach for backend locally. This change requires a significant migration so we wanted to hold off commiting it to the branch until the frontend stuff was ironed out fully.

Maybe for this one case we can go through with both front and back end commits and then circle back quickly on this modal

**Comment by jscholes** [comment]
@johnhbenetech That's fine, for the second modal.  Let's make sure we have an issue open to track that so it doesn't get lost.  That only leaves the link sharing-related stuff for @alexrcabral to comment on for this PR.

**Comment by alexrcabral** [comment]
@jscholes 
@rupeshparab created it correctly according to scope. The full link isn't displayed partly due to space on the screen, and partly for consistency of instruction. I get your point with the link not literally being displayed below, though this is consistent with other sharing sites, which typically show a button to copy the link, that is understood as containing the link.

**Comment by alexrcabral** [comment]
@rupeshparab  To @jscholes last point on not displaying an empty set for when no problems exist in the set, the copy "No Problems Yet" should displayed.

**Comment by jscholes** [comment]
@alexrcabral If it's a full-screen modal, which it should be, I don't think there should be a space issue.  But given the fact that Mathshare is targeting maximum accessibility, particularly for those with learning disabilities or other cognitive concerns, we must be careful about the wording irrespective of how other sites do it.  If you say there is a link, and there is no link, that's not accurate.

**Comment by sinabahram** [comment]
Hope this is making it on a call agenda since we seem to not be landing on a shared understanding for this share button.

**Comment by alexrcabral** [comment]
@sinabahram I've added a bit of time in the agenda tomorrow to touch base on this

**Comment by johnhbenetech** [comment]
@alexrcabral are there any details from the call on further actions required here? I'd like to get some version of this committed so we can start QA testing. We can always break out additional tasks for UI tweaks once the core functionality is tested

**Comment by jscholes** [comment]
@johnhbenetech From the call: to get this merged, two things need to happen:

1. Issues need to be filed so we don't lose track of the necessary follow-ups for these workflows.  Namely, the fact that the "share my answers" modal still needs to be tested, and that the other sharing one needs to have the link present in a text field for copying.
2. In the meantime, the copy needs to be updated in the modal to not indicate there is a link present when there isn't one.

**Comment by johnhbenetech** [comment]
Thanks @jscholes! Ok @alexrcabral please provide updated copy and spin-out tasks when possible

**Comment by alexrcabral** [comment]
Issue #1241 created to address surfacing the link URL. 

New copy as a temporary placeholder for this release:

### Share My Answers 
“Submit your answers to Google Classroom or Microsoft Teams, or use the button below to copy the shareable link.”

Mockup of 'Share My Answers' modal with the new copy. The title, bulleted list, and buttons remain the same.

### Share Problem Set
“Share your problem set through Google Classroom or Microsoft Teams, or use the button below to copy the shareable link.”

Mockup of 'Share Problem Set' modal with the new copy. The title, bulleted list, and buttons remain the same.

**Pull request merged**
