### PR TITLE
#1074 - add Other option and its custom dimension

### PR DESCRIPTION
**Pull request by rupeshparab**
Ref - https://github.com/benetech/MathShare/issues/1074

### CODE REVIEW

**Comment by rupeshparab** [comment]
There is a minor UI change in this, have added another button on the page where User's choose their roles after logging in first time.

**Comment by jscholes** [comment]
Just as an aside, if you're planning to add parent, teaching assistant, or any other roles in the future, that also strengthens the dropdown suggestion.  For student and other, pressing "Next" will just save their data.  For teachers, it will take them to the teacher-specific options.

**Comment by johnhbenetech** [comment]
@alexrcabral can we get input on this?

**Comment by alexrcabral** [comment]
Thanks @jscholes, I agree with these changes. We should move forward with it as a dropdown select with the options "Teacher", "Student", and "Other", followed by a Next button.

**Comment by johnhbenetech** [comment]
@rupeshparab can you review the new suggestion and adjust accordingly?

**Comment by rupeshparab** [comment]
@johnhbenetech 
I have changed user type selection to a dropdown

@alexrcabral Can you check if it looks right?
image

**Comment by rupeshparab** [comment]
@jscholes
I have updated the PR

@alexrcabral 
Attaching a screenshot of the UI
image

**Comment by alexrcabral** [comment]
@rupeshparab Looks good! Only change is the button currently labelled "Confirm" should be labelled "Next", since it's one step in the sign-up process rather than a standalone confirmation.

**Comment by rupeshparab** [comment]
@alexrcabral
In case the user selects Student, it will be a single step
For the students after they click Next they will be redirected to /app or page from where they clicked sign-in and shown a success message

**Comment by johnhbenetech** [comment]
@rupeshparab let's change to 'Next' for everyone for now and get this merged

**Pull request merged**
