### PR TITLE
#1031 - add common nav bar to problem page

### PR DESCRIPTION
**Pull request by rupeshparab**
Ref - https://github.com/benetech/MathShare/issues/1031

### CODE REVIEW

**Comment by rupeshparab** [comment]
@jscholes 
I have discussed Review Deploys as a solution with @johnhbenetech for PR reviews, he will be discussing it with the systems team. For now I have merged this PR to test it on QA env.

**Comment by jscholes** [comment]
@rupeshparab Thanks.  This is mostly fine, except for the two items below:

1. There are two "Skip to Main Content" links, one which is the first child of the `<main>`.  This is unnecessary and the second one should be removed.
2. The "back to all problems" button should be located after the `<h1>`, not before it.  This is particularly important here, because the `<h1>` receives focus automatically so we are basically saying "start here".

**Comment by rupeshparab** [comment]
@jscholes 
I have removed the second Skip to Main Content and raised a PR: https://github.com/benetech/MathShare/pull/1145

I had a doubt in your 2nd point, do you mean I just need to change the arrangement in dom to place the heading before the back button and using css to show the button before heading or should the button also appear after heading.

**Comment by jscholes** [comment]
@rupeshparab As we are explicitly placing focus on the `<h1>`, it would be better for the button to appear after it.  Otherwise, pressing Tab from the user's initial focus point will seem to go backwards.

**Pull request merged**
