### PR TITLE
#976 - Benefits for Signing In

### PR DESCRIPTION
**Pull request by rupeshparab**
Ref - https://github.com/benetech/MathShare/issues/976

### CODE REVIEW

**Comment by johnhbenetech** [comment]
@alexrcabral can we get an opinion here?

**Comment by alexrcabral** [comment]
@jscholes I understand your point for new users. However, since the primary use case of the main sign-in modal would be for returning users, it may make more sense to keep it below the login options. They would already be aware of the benefits, and it would be one more option to navigate through every time they need to get to their goal (signing in).

**Comment by jscholes** [comment]
@alexrcabral I'll counter by saying that if a user is operating a screen reader, has the screen magnified or zoomed, or otherwise cannot scan the page for whatever other reason, they will likely remain unaware of the benefits of signing in altogether.

**Comment by alexrcabral** [comment]
@jscholes The link is not intended for individuals who would otherwise be signing up or signing in. These are intended for users who would not otherwise sign up. 

Primary user: Navigates to sign in, proceeds to sign in. Having the extra link before signing in would be distracting and add extra time every time a user needs to sign in. 

Secondary user: Navigates to sign in, does *not* want to sign in, but is interested in learning more about it. The option to sign in still needs to be first to confirm that this user does not want to sign up or sign in. If they do not want to, then they can learn about the benefits of signing in before closing the modal.

**Comment by johnhbenetech** [comment]
@alexrcabral can you clarify final decision

**Comment by alexrcabral** [comment]
@jscholes If there's anything else I'm overlooking in the user flows please let me know today. 

@rupeshparab Good to proceed with this pull.

**Pull request merged**
