### PR TITLE
#1083 - add getting started page

### PR DESCRIPTION
**Pull request by rupeshparab**
ref - https://github.com/benetech/MathShare/issues/1083

### CODE REVIEW

**Comment by alexrcabral** [comment]
@benetechMatt I know you have the best understanding on the structure you wanted for this content, please give input on @jscholes' first two points.

@jscholes To your last point universal nav should be on all the application portions of the site (e.g. not exclusively accessed from the homepage) as of this upcoming release (#1031). 

@rupeshparab if you could add the universal nav bar (e.g. #1031) to this page that would be much appreciated.

**Comment by benetechMatt** [comment]
@jscholes this was originally written for educators who sometimes consider assigning/sharing the set with students as part of the creation process. Since we're opening this up to more independent student use I've changed it to a new "sharing" section.  I also added a section for students turning in sets as well to support this change.

**Comment by rupeshparab** [comment]
I have updated the "Deleting a Step" text and added the common header on the getting started page

**Comment by johnhbenetech** [comment]
@rupeshparab Please review matt's changes in the box file on the original task for the updated structure

**Comment by rupeshparab** [comment]
@johnhbenetech 
I have updated the content based on the changes in box file

**Comment by alexrcabral** [comment]
@benetechMatt I assume there is a reason for both "Sharing/Turning in Answered Problem Sets" and "Sharing Your Answered Problem Set" so I'll leave as-is, but they'll share the same copy. 

@jscholes @rupeshparab Updates to content: 

[H3] Adding a Problem to a Set

6. All problems are listed above the math editor in the section titled “Add problem(s) to Problem Set”. You can rearrange these using the two corresponding arrow buttons after each problem. 

[H3] Sharing Sets with Students 
1. To share a problem set, go to the "Problem Set Actions" in the upper right corner of the problem set page. This should show options for Share Permalink, Google Classroom, and Microsoft Teams.
2. When someone opens the link you shared, they will be able to answer the problems and share their work back with you.
3. Anyone you share with in this way will not be able to edit the underlying problems. 

[H3] Sharing/Turning in Answered Problem Sets
1. To share a problem set, go to the "Problem Set Actions" in the upper right corner of the problem set page. This should show options for Share Permalink, Google Classroom, and Microsoft Teams.
2. When someone opens the link you shared, they will be able to view your steps.
3. Anyone you share with in this way will not be able to change your work. 

[H3] Sharing Your Answered Problem Set
1. To share a problem set, go to the "Problem Set Actions" in the upper right corner of the problem set page. This should show options for Share Permalink, Google Classroom, and Microsoft Teams.
2. When someone opens the link you shared, they will be able to view your steps.
3. Anyone you share with in this way will not be able to change your work. 

@rupeshparab I've also updated the doc with these changes. Only thing missing is the small typo "aproblem" is in the code rather than the content doc.

**Comment by rupeshparab** [comment]
I have updated the text

**Comment by johnhbenetech** [comment]
I'm gonna merge this since structure/content has been updated and we'd like to release this weekend

**Pull request merged**
