### PR TITLE
Feature/#831 fix landmark issues in audit

### PR DESCRIPTION
**Pull request by rupeshparab**

### CODE REVIEW

**Comment by jscholes** [comment]
@rupeshparab - thanks for taking the initiative to integrate Axe, and act based on its findings.  However, two things:

1. We should have a chance to comment on anything it finds, before changes are merged.  Automated testing is not a panacea, and it will get things wrong.
2. Could you fill in descriptions of what changes you've made for each PR?  I can see the individual commits, but they don't really tell me anything currently.

**Comment by jscholes** [comment]
@rupeshparab - for example, all pages now have a `<main>` wrapped around their entire contents, including headers, footers and everything inbetween.  Meanwhile, the actual `<main>` elements wrapping the main region have been removed.

This is actively moving the accessibility of the application backwards in a serious way, not forwards.  And I'll be frank, nobody on the project has time for that.

**Comment by rupeshparab** [comment]
@jscholes 
Thanks for checking this, I was trying to fix 'Ensures all page content is contained by landmarks' warning shown in Axe
You can find its details in this action logs:
https://github.com/benetech/MathShare/commit/900bce79098c774aa702198450c2981681d31e1f/checks?check_suite_id=364936980

**Comment by jscholes** [comment]
@rupeshparab - one reason for that is that the dashboard has no main landmark region.  You can fix it by exchanging the `<div>` with `id="mainContainer"` for a `<main>`.  There may be other examples, but the key is to check and fix them on a case-by-case basis.

**Comment by rupeshparab** [comment]
@jscholes 
I tried following this approach in the SignIn component, it doesn't seem to fix the issue in Axe audit.
I am thinking that I can follow the approach in https://github.com/benetech/MathShare/pull/853/commits/cc01e75b8193c196417d8ef6623b01246047cc94 to have a common <main> container at the outermost level, but while doing this I need to ensure that <header> and <footer> stays outside.

Let me know if I need to ensure something else while doing this.

**Comment by jscholes** [comment]
@rupeshparab - Axe is recommending that all content should be wrapped inside a landmark region, because landmark regions act to semantically structure content.  They help users understand and navigate pages.  So this error cannot be fixed by a catch-all solution which fixes the mark-up, while not addressing the underlying concern.

I believe that the Axe warning is partially being caused by the fact that in index.js, there is a `<div>` (`id="contentContainer"`), as well as the `AriaLiveAnnouncer` component, located outside of any region.  If you put AriaLiveAnnouncer inside the `<footer>`, and get rid of the `<div>`, that will address two of the violations.  Then, a `<main>` for the Dashboard will fix another (as indicated in my previous comment).

At that point, we can see if there are any outstanding instances of this problem.  But the "Sign In" page shouldn't need any changes to address it, because it already has a `<main>`.

**Comment by rupeshparab** [comment]
@jscholes 
Thanks, will try it out

**Pull request merged**
